---
# ansible-playbook copy.yml
# this module is used to copy a file
# from current location to aws_inspector_target

- name: copy a file to hosts
  hosts: myservers
  become: true
  #fast_gathering: false
  tasks:
    - name: copy a file to the home directory of user  
      copy: 
         src: ~/.ansible/config_files/file2.txt
         dest: ~/file2.txt
         mode: 0766
